{{- $app := .Values.deployments.app -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: {{ .Release.Namespace }}
  labels:
    app: backend
    {{- include "backend.labels" . | nindent 4 }}
spec:
  replicas: {{ $app.replicaCount }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      annotations: {}
      labels:
        app: backend
    spec:
      serviceAccountName: backend-sa
      containers:
      - name: app
        image: "{{ template "image" . }}"
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ $app.containerPort }}
          protocol: TCP
      imagePullSecrets:
        {{- range $.Values.global.imagePullSecrets }}
        - name: {{ .name }}
        {{- end }}