{{- $app := .Values.deployments.app -}}
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    {{- include "backend.labels" $ | nindent 4 }}
spec:
  type: {{ $app.service.type }}
  ports:
    - port: {{ $app.service.port }}
      targetPort: {{ $app.containerPort }}
      protocol: TCP
      name: http
  selector:
    app: backend