{{- $app := .Values.deployments.app -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: backend
  labels:
    {{- include "kvasmt-backend.labels" $ | nindent 4 }}
spec:
  hosts:
    {{- range $app.virtualservice.hosts }}
    - {{ . }}
    {{- end }}
  gateways:
    {{- range $app.virtualservice.gateways }}
    - {{ . }}
    {{- end }}
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: backend.demo.svc.cluster.local
        port:
          number: {{ $app.service.port }}