global:
  image:
    registry: 913524938299.dkr.ecr.ap-southeast-1.amazonaws.com
    repository: kvasmt/backend-backend
    tag: latest
    pullPolicy: Always

deployments:
  app:
    command: ""
    replicaCount: 1
    containerPort: 5000
    service:
      type: ClusterIP
      port: 80
    virtualservice: {}

