global:
  image:
    registry: 913524938299.dkr.ecr.ap-southeast-1.amazonaws.com
    repository: kvasmt/development-frontend
    tag: frontend-app-5
    pullPolicy: Always

deployments:
  app:
    replicaCount: 1
    containerPort: 80
    service:
      type: ClusterIP
      port: 80
    virtualservice:
      hosts:
        - "demo.kietvo.vn"
      gateways:
        - istio-ingress/istio-ingressgateway

