apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  interval: 5m
  dependsOn:
    - name: istio-base
      namespace: istio-system
  chart:
    spec:
      chart: istiod
      sourceRef:
        kind: HelmRepository
        name: istio
      version: 1.22.2
      interval: 1m
  values:
    meshConfig:
      ingressService: istio-ingress
      ingressSelector: ingress
      accessLogFile: /dev/stdout
      accessLogEncoding: JSON      
    global:
      proxy:
        terminationDrainDuration: 60s